### ISSUE TITLE
Morty Helmet MkII Materials Checklist

### ISSUE THREAD

**Issue by ppak10** [ppak10/Morty-Helmet#2]
# Materials Checklist
The following building materials will be checked off when they have gathered
- [ ] Plastic Globe for Helmet Structure
- [x] VR Device for Sight
  - [x] Samsung Galaxy S8
  - [x] Gear VR 
- [ ] Headphones for Sound
  - [x] V-Moda Headphones
- [ ] Batteries to power these devices
